import type { ActionStoreRow } from '@/hooks/useActionStoreRowsQuery'
import { useCallback } from 'react'
import { isAutogeneratedRow, type GridRenderCellParams } from '@mui/x-data-grid-pro'
import { useNavigate } from 'react-router-dom'
import { ActionsMenu } from './ActionsMenu'

const getNavigateOptions = ({ actionStore, dependantActionStore, store }: ActionStoreRow) => ({
  state: { addActionStore: actionStore, removeActionStore: dependantActionStore, store }
})

export const ActionColumn = ({ row }: GridRenderCellParams<ActionStoreRow>) => {
  const navigate = useNavigate()

  const { actionStore, dependantActionStore, product } = row

  const handleAdditionEdit = useCallback(() => {
    navigate('edit-swap/Add', getNavigateOptions(row))
  }, [navigate, row])

  const handleRemovalEdit = useCallback(() => {
    navigate('edit-swap/Remove', getNavigateOptions(row))
  }, [navigate, row])

  const handleNotesEdit = useCallback(() => {
    navigate('edit-notes', getNavigateOptions(row))
  }, [navigate, row])

  const handleEditProducts = useCallback(() => {
    navigate('edit-products', getNavigateOptions(row))
  }, [navigate, row])

  const handleDelete = useCallback(() => {
    navigate(`delete-swap/${actionStore.id}`)
  }, [navigate, actionStore])

  if (isAutogeneratedRow(row) || actionStore.actionType === 'Remove' || product) {
    return null
  }

  return (
    <ActionsMenu
      onDelete={handleDelete}
      onAdditionEdit={handleAdditionEdit}
      onRemovalEdit={handleRemovalEdit}
      onNotesEdit={handleNotesEdit}
      onProductsEdit={handleEditProducts}
      hasNote={Boolean(actionStore.note)}
      translate={Boolean(dependantActionStore)}
      row={row}
    />
  )
}
