import type { ActionSet } from '@/api/types.generated'
import type { ActionStoreRow } from '@/hooks/useActionStoreRowsQuery'
import type { GridBasicGroupNode, GridCellParams, GridRowParams, GridTreeNode } from '@mui/x-data-grid-pro'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import Stack from '@mui/material/Stack'
import { styled } from '@mui/material/styles'
import { gridSortedRowIdsSelector, isAutogeneratedRow, useGridApiRef } from '@mui/x-data-grid-pro'
import { defineMessages, FormattedMessage } from 'react-intl'
import { useNavigate } from 'react-router-dom'
import api from '@/api'
import CollapseSection from '@/components/CollapseSection'
import { DataGrid } from '@/components/DataGrid/DataGrid'
import ErrorMessage from '@/components/ErrorMessage'
import Search from '@/components/PlanSearch'
import { useAllRelevantSubcategories } from '@/hooks/arteli'
import { useExpansion } from '@/hooks/useExpansion'
import { PATH_MANUAL_SWAP } from '@/routes'
import { allItemsQuery } from '@/utils/allItemsQuery'
import { usePresentationRows } from '../../usePresentationRows'
import { GridContext } from './GridContext'
import { PlanFilters } from './PlanFilters'
import { ALL_CATEGORIES_ID, ALL_SUBCATEGORIES_ID, useFilters } from './useFilters'
import { useGridConfiguration } from './useGridConfiguration'
import { useGridContextValue } from './useGridContextValue'

const messages = defineMessages({
  empty: { defaultMessage: 'No Rows To Show', id: '+zndIf' },
  create: { defaultMessage: 'Create Swap', id: 'ZZW5Yz' }
})

const StyledButton = styled(Button)(() => ({
  '&.MuiButton-root': {
    padding: '7px 16px'
  }
}))

const getCellClassName = ({ rowNode, colDef, row }: GridCellParams<ActionStoreRow>) => {
  const borderTop = row?.borderTop ? 'border-top' : ''

  if (colDef.field === 'actionStore.id') return [borderTop, 'action-cell'].join(' ')

  if (rowNode.type == 'group' && rowNode.depth === 0) {
    return ['group-cell', borderTop].join(' ')
  }

  return borderTop
}

const getRowClassName = ({ row }: GridRowParams<ActionStoreRow>) => {
  if (isAutogeneratedRow(row)) return ''

  if (row.actionStore.actionType === 'Add') return 'border-x'

  return ''
}

const getTreeDataPath = ({ store, actionStore, product }: ActionStoreRow) => [
  store.id,
  actionStore.id,
  ...(product ? [product.id] : [])
]

const useAllGroupsQuery = allItemsQuery(api.Arteli.Groups.findAll)

export const PlanList = ({
  rows: rows_,
  isFetching
}: {
  actionSet?: ActionSet
  rows: readonly ActionStoreRow[]
  isFetching: boolean
}) => {
  const gridApiRef = useGridApiRef()
  const filters = useFilters()
  const { categoryId, storeIds, subcategoryIds } = filters
  const { data: subcategories } = useAllRelevantSubcategories()
  const navigate = useNavigate()
  const [query, setQuery] = useState('')
  const { rows } = usePresentationRows(rows_)
  const contextValue = useGridContextValue(rows)
  const { storeStatues } = contextValue

  const { collapseAll, expandAll, isGroupExpandedByDefault, setExpanded } = useExpansion(gridApiRef)

  const allSubcategoriesSelected = useMemo(
    () =>
      subcategoryIds.includes(ALL_SUBCATEGORIES_ID) ||
      (categoryId &&
        subcategories
          ?.filter(({ categoryIds }) => categoryIds.includes(categoryId))
          .every(({ id }) => subcategoryIds.includes(id))),
    [categoryId, subcategories, subcategoryIds]
  )

  const { data: groupsFromBE, isFetching: isFetchingGroupsFromBe } = useAllGroupsQuery({
    params: { search: query },
    enabled: query.length > 2
  })

  const ids = useMemo(() => {
    const allCategoriesSelected = categoryId === ALL_CATEGORIES_ID
    const idsFromBE = (groupsFromBE ?? []).map((_) => _.id)

    let searchedRows = rows.filter(
      ({ category, store, subcategory }) =>
        (allCategoriesSelected || categoryId === category.id) &&
        storeIds.includes(store.id) &&
        (allSubcategoriesSelected || (subcategory && subcategoryIds.includes(subcategory.id)))
    )

    if (query.length > 0) {
      searchedRows = searchedRows.filter(({ group }) => idsFromBE.includes(group.id))
    }

    return searchedRows.map(({ actionStore }) => actionStore.id)
  }, [allSubcategoriesSelected, categoryId, groupsFromBE, query.length, rows, storeIds, subcategoryIds])

  const { columns, groupingColDef } = useGridConfiguration({ context: contextValue })

  const isCalledRef = useRef(false)

  useEffect(() => {
    if (isCalledRef.current || !rows.length) return

    const gridApi = gridApiRef?.current

    if (!gridApi) return

    isCalledRef.current = true

    const storeIds = Object.keys(storeStatues)

    gridSortedRowIdsSelector(gridApiRef)
      .map((id) => gridApi.getRowNode(id))
      .filter((node: GridTreeNode | null) => {
        if (!node) return false

        const storeId = (node as GridBasicGroupNode).groupingKey

        if (!storeId) return false

        return storeIds.includes(storeId.toString())
      })
      .forEach((node: GridTreeNode | null) => {
        if (!node) return

        setExpanded(node.id.toString(), true)
        gridApi.setRowChildrenExpansion(node.id, true)
      })
  }, [storeStatues, gridApiRef, rows, setExpanded])

  const handleOpenSwap = useCallback(() => {
    navigate({ pathname: PATH_MANUAL_SWAP, search: location.search })
  }, [navigate])

  const handleChangeQuery = useCallback((query: string) => {
    setQuery(query.trim().length > 2 ? query.trim() : '')
  }, [])

  const filteredRows = useMemo(() => {
    return rows.filter(
      ({ actionStore }) =>
        (actionStore.dependentId && ids.includes(actionStore.dependentId)) ||
        (actionStore.principalId && ids.includes(actionStore.principalId)) ||
        ids.includes(actionStore.id)
    )
  }, [ids, rows])

  return (
    <>
      <PlanFilters {...filters} />
      <CollapseSection onExpand={expandAll} onCollapse={collapseAll}>
        <Stack direction="row" spacing={2} alignItems="start" width="50%">
          <Search onChange={handleChangeQuery} isFetching={isFetchingGroupsFromBe} count={ids.length} />
          <StyledButton variant="outlined" color="primary" onClick={handleOpenSwap} sx={{ minWidth: 140 }}>
            <FormattedMessage {...messages.create} />
          </StyledButton>
        </Stack>
      </CollapseSection>
      {Boolean(rows.length) && (
        <GridContext.Provider value={contextValue}>
          <DataGrid
            apiRef={gridApiRef}
            treeData
            getTreeDataPath={getTreeDataPath}
            rows={filteredRows}
            columns={columns}
            groupingColDef={groupingColDef}
            rowSelection={false}
            getCellClassName={getCellClassName}
            getRowClassName={getRowClassName}
            isGroupExpandedByDefault={isGroupExpandedByDefault}
            // standard props
            disableColumnSorting
          />
        </GridContext.Provider>
      )}
      {!isFetching && rows?.length === 0 && (
        <Box sx={{ height: 240, position: 'relative' }}>
          <ErrorMessage>
            <FormattedMessage {...messages.empty} />
          </ErrorMessage>
        </Box>
      )}
    </>
  )
}
