import type { GridContextParams } from './GridContext'
import type { ActionStoreRow } from '@/hooks/useActionStoreRowsQuery'
import type { DataGridProProps, GridColDef } from '@mui/x-data-grid-pro'
import { useMemo } from 'react'
import { isAutogeneratedRow } from '@mui/x-data-grid-pro'
import dayjs from 'dayjs'
import minMax from 'dayjs/plugin/minMax'
import { defineMessages, useIntl } from 'react-intl'
import { CurrencyColumn } from '@/components/grid/CurrencyColumn'
import { TagsColumn } from '@/components/grid/TagsColumn'
import { useCommonLabels } from '@/hooks/useCommonLabels'
import { commonMessages } from '@/utils/messages'
import { ActionColumn } from './ActionColumn'
import { NameColumn } from './NameColumn'

dayjs.extend(minMax)

const statusesMap = {
  'Now on floor': commonMessages.nowOnFloor,
  'No longer on floor': commonMessages.noLongerOnFloor,
  'Inactive Series': commonMessages.seriesInactive
}

const messages = defineMessages({
  storeName: { defaultMessage: 'Store Name', id: 'AarHCY' }
})

export const useGridConfiguration = ({ context }: { context: GridContextParams }) => {
  const { headers } = useCommonLabels()
  const { formatMessage: t } = useIntl()

  const columns = useMemo<GridColDef<ActionStoreRow>[]>(() => {
    return [
      {
        headerName: headers.Tags,
        field: 'productTags',
        valueGetter: (_, row: ActionStoreRow) => (row.product ? row.product.tags : row?.actionStore?.productTagsAny),
        renderCell: TagsColumn,
        autoHeight: true,
        width: 110,
        sortable: false
      },
      {
        headerName: headers.Category,
        field: 'category',
        valueGetter: (category: ActionStoreRow['category'], row) =>
          isAutogeneratedRow(row) ? '' : category.externalId,
        width: 160,
        sortable: false
      },
      {
        headerName: headers.Subcategory,
        field: 'subcategory',
        valueGetter: (subcategory: ActionStoreRow['subcategory'], row) =>
          isAutogeneratedRow(row) ? '' : subcategory?.externalId,
        width: 160,
        sortable: false
      },
      {
        headerName: headers.PredictedSalesSeries,
        field: 'actionStore',
        valueGetter: (actionStore: ActionStoreRow['actionStore'], row, _, gridApiRef) => {
          const storeId = gridApiRef.current.getRowId(row).toString().split('/')[1]

          return isAutogeneratedRow(row)
            ? context.storeImpact[storeId]
            : row.product
              ? row.recStore?.predictedSales
              : actionStore.predictedSales
        },
        width: 200,
        sortable: false,
        renderCell: CurrencyColumn
      },
      {
        headerName: headers.Status,
        field: 'status',
        width: 150,
        sortable: false,
        cellClassName: 'column-status',
        valueGetter: (status: ActionStoreRow['status'], row, _, gridApiRef) => {
          const storeId = gridApiRef.current.getRowId(row).toString().split('/')[1]

          return isAutogeneratedRow(row)
            ? context.storeStatues[storeId]
              ? t(commonMessages.needsAttention)
              : ''
            : status && !row.product
              ? t(statusesMap[status])
              : ''
        }
      },
      {
        headerName: '',
        field: 'actionStore.id',
        renderCell: ActionColumn,
        sortable: false,
        minWidth: 120,
        maxWidth: 130
      }
    ]
  }, [
    context.storeImpact,
    context.storeStatues,
    headers.Category,
    headers.PredictedSalesSeries,
    headers.Status,
    headers.Subcategory,
    headers.Tags,
    t
  ])

  const groupingColDef: DataGridProProps['groupingColDef'] = useMemo(
    () => ({
      headerName: t(messages.storeName),
      flex: 1,
      renderCell: NameColumn
    }),
    [t]
  )

  return { columns, headers, groupingColDef }
}
