import type { GridContextParams } from './GridContext'
import type { Row } from './useRows'
import { useMemo } from 'react'
import { isAutogeneratedRow, type GridColDef, type DataGridProProps } from '@mui/x-data-grid-pro'
import { defineMessages, useIntl } from 'react-intl'
import { useCommonLabels } from '@/hooks/useCommonLabels'
import { ColumnHeaderWithDescription } from '../grid/ColumnHeaderWithDescription'
import { CurrencyColumn } from '../grid/CurrencyColumn'
import { TagsColumn } from '../grid/TagsColumn'
import { ActionColumn } from './components/ActionColumn'
import { NameColumn } from './components/NameColumn'

const messages = defineMessages({
  swapImpact: { defaultMessage: 'Swap Impact', id: 'CTiktq' },
  removalSeriesName: { defaultMessage: 'Removal Series Name', id: 'JhAcii' },
  predictedSalesHint: {
    defaultMessage:
      'The difference between the predicted sales of the series added and the series removed from this store',
    id: 'k1v9fJ'
  }
})

export const useGridConfiguration = ({ context }: { context: GridContextParams }) => {
  const { headers } = useCommonLabels()
  const { formatMessage: t } = useIntl()

  const columns = useMemo<GridColDef<Row>[]>(() => {
    return [
      // {
      //   headerName: 'Debug',
      //   field: 'debug',
      //   valueGetter: (_, { group, recGroup }) =>
      //     group?.id ? `${group?.id} ${recGroup?.productFlagsAny.toString(2)} ${recGroup?.productTagsAll.toString(2)}` : '-',
      //   sortable: false,
      //   width: 160
      // },
      {
        headerName: headers.Tags,
        field: 'recGroup.productTagsAny',
        valueGetter: (_, row) => row?.recGroup?.productTagsAny,
        renderCell: TagsColumn,
        cellStyle: () => ({ whiteSpace: 'pre' }),
        // autoHeight: true,
        sortable: false,
        width: 160
      },
      {
        headerName: headers.AvgMonthlyPastSales,
        field: 'recGroup.pastSales',
        valueGetter: (_, row) => row?.recGroup?.pastSales,
        renderCell: CurrencyColumn,
        sortable: false,
        width: 160
      },
      {
        headerName: t(messages.swapImpact),
        field: 'recGroup',
        valueGetter: (recGroup: Row['recGroup'], row, _, gridApiRef) => {
          const storeId = gridApiRef.current.getRowId(row).toString().split('/')[1]
          return isAutogeneratedRow(row) ? context.swapImpact[storeId] : recGroup?.predictedSales
        },
        renderCell: CurrencyColumn,
        sortable: false,
        description: t(messages.predictedSalesHint),
        renderHeader: ColumnHeaderWithDescription,
        hideSortIcons: true,
        minWidth: 132,
        width: 160
      },
      {
        headerName: '',
        field: 'id',
        renderCell: ActionColumn,
        sortable: false,
        minWidth: 170
      }
    ]
  }, [context, headers.AvgMonthlyPastSales, headers.Tags, t])

  const groupingColDef: DataGridProProps['groupingColDef'] = useMemo(
    () => ({
      headerName: t(messages.removalSeriesName),
      flex: 1,
      renderCell: NameColumn
    }),
    [t]
  )

  return { columns, headers, groupingColDef }
}
