import type { GridContextParams } from './GridContext'
import type { Row } from './useRows'
import { useMemo } from 'react'
import { isAutogeneratedRow, type DataGridProProps, type GridColDef } from '@mui/x-data-grid-pro'
import { defineMessages, useIntl } from 'react-intl'
import { CurrencyColumn } from '@/components/grid/CurrencyColumn'
import { useCommonLabels } from '@/hooks/useCommonLabels'
import { commonMessages } from '@/utils/messages'
import { CategoryHeader } from './components/CategoryHeader'
import { NameColumn } from './components/NameColumn'

const messages = defineMessages({
  daysOnFloor: { defaultMessage: 'Days on Floor', id: 'w10kKG' }
})

export const useGridConfiguration = ({ context }: { context: GridContextParams }) => {
  const { headers } = useCommonLabels()
  const { formatMessage: t } = useIntl()

  const columns = useMemo<GridColDef<Row>[]>(
    () => [
      {
        headerName: headers.Id,
        field: 'product.externalId',
        valueGetter: (product: Row['product'], row, _, gridApiRef) => {
          if (isAutogeneratedRow(row)) {
            const ids = gridApiRef.current.getRowId(row).toString().split('/')
            if (ids.length === 2) {
              return context.stats[ids[1]]?.groupIds?.join(', ')
            }
            if (ids.length === 3) {
              return context.subgroupsById[ids[2]]?.externalId
            }
            if (ids.length === 4) {
              return context.subgroupsById[ids[2].split('-')[0]]?.externalId
            }
            return product?.externalId
          }
          return row.product?.externalId
        },
        sortable: false,
        width: 120
      },
      {
        headerName: headers.Category,
        field: 'category',
        valueGetter: (category: Row['category'], row, _, gridApiRef) => {
          if (isAutogeneratedRow(row)) {
            const ids = gridApiRef.current.getRowId(row).toString().split('/')
            if (ids.length === 2) {
              return context.stats[ids[1]]?.productCategories.join(', ')
            }
            if (ids.length === 3) {
              return context.sub[ids[2]]?.productCategories.join(', ')
            }
            if (ids.length === 4) {
              if (ids[3] === 'Component') {
                return context.comp[ids[2].split('-')[0]]?.productCategories.join(', ')
              }
              if (ids[3] === 'Kit') {
                return context.kit[ids[2].split('-')[0]]?.productCategories.join(', ')
              }
            }
            return category?.externalId
          }
          return row.category?.externalId
        },
        renderHeader: CategoryHeader,
        sortable: false,
        width: 140
      },
      {
        headerName: headers.Subcategory,
        field: 'subcategory',
        width: 140,
        sortable: false,
        valueGetter: (subcategory: Row['subcategory'], row, _, gridApiRef) => {
          if (isAutogeneratedRow(row)) {
            const ids = gridApiRef.current.getRowId(row).toString().split('/')
            if (ids.length === 2) {
              return context.stats[ids[1]]?.productSubcategories.join(', ')
            }
            if (ids.length === 3) {
              return context.sub[ids[2]]?.productSubcategories.join(', ')
            }
            if (ids.length === 4) {
              if (ids[3] === 'Component') {
                return context.comp[ids[2].split('-')[0]]?.productSubcategories.join(', ')
              }
              if (ids[3] === 'Kit') {
                return context.kit[ids[2].split('-')[0]]?.productSubcategories.join(', ')
              }
            }
            return subcategory?.externalId
          }
          return row.subcategory?.externalId
        }
      },
      {
        headerName: t(commonMessages.pastSales90Days),
        field: 'recStore.pastSales',
        renderCell: CurrencyColumn,
        sortable: true,
        width: 120,
        valueGetter: (recStore: Row['recStore'], row, _, gridApiRef) => {
          if (isAutogeneratedRow(row)) {
            const ids = gridApiRef.current.getRowId(row).toString().split('/')
            if (ids.length === 2) {
              return context.stats[ids[1]]?.pastSales.reduce((a, b) => a + b, 0)
            }
            if (ids.length === 3) {
              return context.sub[ids[2]]?.pastSales.reduce((a, b) => a + b, 0)
            }
            if (ids.length === 4) {
              if (ids[3] === 'Component') {
                return context.comp[ids[2].split('-')[0]]?.pastSales.reduce((a, b) => a + b, 0)
              }
              if (ids[3] === 'Kit') {
                return context.kit[ids[2].split('-')[0]]?.pastSales.reduce((a, b) => a + b, 0)
              }
            }
            return recStore?.pastSales
          }
          return row.recStore?.pastSales
        }
      },
      {
        headerName: t(commonMessages.predictedSales90Days),
        field: 'recStore.predictedSales',
        renderCell: CurrencyColumn,
        valueGetter: (recStore: Row['recStore'], row, _, gridApiRef) => {
          if (isAutogeneratedRow(row)) {
            const ids = gridApiRef.current.getRowId(row).toString().split('/')
            if (ids.length === 2) {
              return context.stats[ids[1]]?.predictedSales.filter(Boolean).reduce((a, b) => a + b, 0)
            }
            if (ids.length === 3) {
              return context.sub[ids[2]]?.predictedSales.filter(Boolean).reduce((a, b) => a + b, 0)
            }
            if (ids.length === 4) {
              if (ids[3] === 'Component') {
                return context.comp[ids[2].split('-')[0]]?.predictedSales.filter(Boolean).reduce((a, b) => a + b, 0)
              }
              if (ids[3] === 'Kit') {
                return context.kit[ids[2].split('-')[0]]?.predictedSales.filter(Boolean).reduce((a, b) => a + b, 0)
              }
            }
            return recStore?.predictedSales ?? 0
          }
          return row.recStore?.predictedSales ?? 0
        },
        sortable: true,
        width: 155
      },
      {
        headerName: t(messages.daysOnFloor),
        field: 'daysOnFloor',
        valueGetter: (daysOnFloor: Row['daysOnFloor'], row, _, gridApiRef) => {
          if (isAutogeneratedRow(row)) {
            const ids = gridApiRef.current.getRowId(row).toString().split('/')
            if (ids.length === 2) {
              return Math.max(...(context.stats[ids[1]]?.daysOnFloor ?? []))
            }
            if (ids.length === 3) {
              return Math.max(...(context.sub[ids[2]]?.daysOnFloor ?? []))
            }
            if (ids.length === 4) {
              if (ids[3] === 'Component') {
                return Math.max(...(context.comp[ids[2].split('-')[0]]?.daysOnFloor ?? []))
              }
              if (ids[3] === 'Kit') {
                return Math.max(...(context.kit[ids[2].split('-')[0]]?.daysOnFloor ?? []))
              }
            }
            return daysOnFloor
          }
          return row.daysOnFloor
        },
        sortable: true,
        width: 110,
        renderCell: ({ value }) => (isNaN(value) || !isFinite(value) ? '-' : value)
      }
    ],
    [
      context.comp,
      context.kit,
      context.stats,
      context.sub,
      context.subgroupsById,
      headers.Category,
      headers.Id,
      headers.Subcategory,
      t
    ]
  )

  const groupingColDef: DataGridProProps['groupingColDef'] = useMemo(
    () => ({
      headerName: headers.Name,
      flex: 1,
      renderCell: NameColumn
    }),
    [headers.Name]
  )

  return { columns, groupingColDef }
}
