import type { OutletContext } from '../OutletContext'
import type { ActionCompletionStatus, Category } from '@/api/types.generated'
import type { ActionStoreRow } from '@/hooks/useActionStoreRowsQuery'
import type {
  GridBasicGroupNode,
  GridCellParams,
  GridFilterModel,
  GridRowParams,
  GridTreeNode
} from '@mui/x-data-grid-pro'
import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { random } from '@arteli/utils'
import Box from '@mui/material/Box'
import { styled } from '@mui/material/styles'
import Typography from '@mui/material/Typography'
import { GridLogicOperator, gridSortedRowIdsSelector, isAutogeneratedRow, useGridApiRef } from '@mui/x-data-grid-pro'
import { createPortal } from 'react-dom'
import { FormattedMessage, defineMessages } from 'react-intl'
import { useOutletContext, Outlet } from 'react-router-dom'
import { TransitionGroup } from 'react-transition-group'
import api from '@/api'
import CollapseSection from '@/components/CollapseSection'
import { DataGrid } from '@/components/DataGrid/DataGrid'
import ErrorMessage from '@/components/ErrorMessage'
import Search from '@/components/PlanSearch'
import { useExpansion } from '@/hooks/useExpansion'
import { useDateRange } from '@/pages/Dashboard/useDateRange'
import { needsAttention, unique } from '@/utils'
import { allItemsQuery } from '@/utils/allItemsQuery'
import { DateRangePicker } from '../DateRangePicker'
import { GridContext } from './GridContext'
import { useGridConfiguration } from './useGridConfiguration'
import { useGridContextValue } from './useGridContextValue'
import { useRows } from './useRows'

const SearchContainer = styled('div')(() => ({
  display: 'flex',
  alignContent: 'baseline',
  width: '40%',
  paddingRight: 1
}))

const messages = defineMessages({
  auditsDescription: { defaultMessage: 'View the status of approved swaps.', id: 'LYjXpA' },
  emptyList: { defaultMessage: 'No swaps exist for the selected date range', id: '6uSuAE' }
})

const getCellClassName = ({ rowNode, colDef, row }: GridCellParams<ActionStoreRow>) => {
  const borderTop = row?.borderTop ? 'border-top' : ''

  if (colDef.field === 'actionStore.id') return [borderTop, 'action-cell'].join(' ')

  if (rowNode.type == 'group' && rowNode.depth === 0) {
    return ['group-cell', borderTop].join(' ')
  }

  return borderTop
}

const getRowClassName = ({ row }: GridRowParams<ActionStoreRow>) => {
  if (isAutogeneratedRow(row)) return ''

  if (row.actionStore.actionType === 'Add') return 'border-x'

  return ''
}

const getTreeDataPath = ({ store, actionStore, product }: ActionStoreRow) => [
  store.id,
  actionStore.id,
  ...(product ? [product.id] : [])
]

const useAllGroupsQuery = allItemsQuery(api.Arteli.Groups.findAll)

export function HistoricalSwaps() {
  const gridApiRef = useGridApiRef()
  const { from, to, setFrom, setTo } = useDateRange()
  const { buttonContainerRef } = useOutletContext<OutletContext>()
  const [query, setQuery] = useState('')
  const { rows, isFetching } = useRows()
  const contextValue = useGridContextValue({ rows })
  const { columns, groupingColDef } = useGridConfiguration({ context: contextValue })
  const {
    selectedActionCompletionStatuses,
    selectedCategoryExternalIds,
    swapStatusesByStoreId,
    setCategoryExternalIds,
    setActionCompletionStatuses
  } = contextValue

  const { collapseAll, expandAll, isGroupExpandedByDefault, setExpanded } = useExpansion(gridApiRef)

  const isAutomaticallyExpandedRef = useRef(false)

  const { data: groupsFromBE, isFetching: isFetchingGroupsFromBe } = useAllGroupsQuery({
    params: { search: query },
    enabled: query.length > 2
  })

  const ids = useMemo(() => {
    const idsFromBE = (groupsFromBE ?? []).map((_) => _.id)
    let searchedRows = rows

    if (query.length > 0) {
      searchedRows = searchedRows.filter(({ group }) => idsFromBE.includes(group.id))
    }

    return searchedRows.map(({ actionStore }) => actionStore.id)
  }, [groupsFromBE, query.length, rows])

  const filteredRows = useMemo(() => {
    return rows.filter(
      ({ actionStore }) =>
        (actionStore.dependentId && ids.includes(actionStore.dependentId)) ||
        (actionStore.principalId && ids.includes(actionStore.principalId)) ||
        ids.includes(actionStore.id)
    )
  }, [ids, rows])

  useEffect(() => {
    setCategoryExternalIds(unique(rows.map(({ category }) => category.externalId)))
    setActionCompletionStatuses(unique(rows.map(({ actionStore }) => actionStore.completionStatus)))
  }, [rows, setActionCompletionStatuses, setCategoryExternalIds])

  useEffect(() => {
    if (isAutomaticallyExpandedRef.current || !rows.length) return

    isAutomaticallyExpandedRef.current = true

    const gridApi = gridApiRef?.current

    if (!gridApi) return

    const storeIds = Object.entries(swapStatusesByStoreId)
      .filter(([, statuses]) => needsAttention(statuses))
      .map(([storeId]) => storeId)

    gridSortedRowIdsSelector(gridApiRef)
      .map((id) => gridApi.getRowNode(id))
      .filter((node: GridTreeNode | null) => {
        if (!node) return false

        const storeId = (node as GridBasicGroupNode).groupingKey

        if (!storeId) return false

        return storeIds.includes(storeId.toString())
      })
      .forEach((node: GridTreeNode | null) => {
        if (!node) return

        setExpanded(node.id.toString(), true)
        gridApi.setRowChildrenExpansion(node.id, true)
      })
  }, [rows, swapStatusesByStoreId, gridApiRef, setExpanded])

  const filterModel = useMemo<GridFilterModel>(() => {
    const categoryIds =
      selectedCategoryExternalIds.length > 0 ? selectedCategoryExternalIds : [random.String as Category['externalId']]

    const swapStatues =
      selectedActionCompletionStatuses.length > 0
        ? selectedActionCompletionStatuses
        : [random.String as ActionCompletionStatus]

    return {
      items: [
        { id: random.String, field: 'category', operator: 'isAnyOf', value: categoryIds },
        { id: random.String, field: 'swapStatus', operator: 'isAnyOf', value: swapStatues }
      ],
      logicOperator: GridLogicOperator.And
    }
  }, [selectedActionCompletionStatuses, selectedCategoryExternalIds])

  const handleChangeQuery = useCallback((query: string) => {
    setQuery(query.trim().length > 2 ? query.trim() : '')
  }, [])

  return (
    <>
      {buttonContainerRef?.current &&
        createPortal(
          <DateRangePicker to={to} from={from} onFromChange={setFrom} onToChange={setTo} />,
          buttonContainerRef.current
        )}
      <Box
        sx={({ sizes }) => ({
          height: `calc(100vh - ${sizes.header.height}px - ${sizes.pageHeader.height}px - ${70}px)`
        })}
      >
        <Typography fontSize={16} mt={3} mb={2}>
          <FormattedMessage {...messages.auditsDescription} />
        </Typography>
        <CollapseSection onExpand={expandAll} onCollapse={collapseAll} gutterBottom={false}>
          <SearchContainer>
            <Search onChange={handleChangeQuery} isFetching={isFetchingGroupsFromBe} count={ids.length} />
          </SearchContainer>
        </CollapseSection>

        {Boolean(rows.length) && (
          <GridContext.Provider value={contextValue}>
            <DataGrid
              apiRef={gridApiRef}
              treeData
              disableColumnFilter
              getTreeDataPath={getTreeDataPath}
              rows={filteredRows}
              columns={columns}
              groupingColDef={groupingColDef}
              rowSelection={false}
              disableColumnSorting
              filterModel={filterModel}
              getCellClassName={getCellClassName}
              getRowClassName={getRowClassName}
              isGroupExpandedByDefault={isGroupExpandedByDefault}
            />
          </GridContext.Provider>
        )}
        {!isFetching && rows?.length === 0 && (
          <Box sx={{ height: 240, position: 'relative' }}>
            <ErrorMessage>
              <FormattedMessage {...messages.emptyList} />
            </ErrorMessage>
          </Box>
        )}
      </Box>
      <TransitionGroup>
        <Suspense>
          <Outlet />
        </Suspense>
      </TransitionGroup>
    </>
  )
}
