import type { ActionStoreRow } from '@/hooks/useActionStoreRowsQuery'
import { useContext } from 'react'
import { styled, useTheme } from '@mui/material/styles'
import Typography from '@mui/material/Typography'
import { isAutogeneratedRow, useGridApiContext, type GridRenderCellParams } from '@mui/x-data-grid-pro'
import { defineMessages, useIntl } from 'react-intl'
import { needsAttention } from '@/utils'
import { commonMessages } from '@/utils/messages'
import { GridContext } from './GridContext'

const Base = styled('div')(() => ({
  display: 'flex',
  alignItems: 'center',
  height: '100%'
}))

const actionCompletionStatusMessages = defineMessages({
  Pending: { defaultMessage: 'Pending', id: 'eKEL/g' },
  Completed: { defaultMessage: 'Completed', id: '95stPq' },
  Expired: { defaultMessage: 'Expired', id: 'RahCRH' },
  Inactive: { defaultMessage: 'Inactive', id: '6Tps09' },
  Overdue: { defaultMessage: 'Overdue (as of {date})', id: '/A/HAj' }
})

export const SwapStatusColumn = ({ row }: GridRenderCellParams<ActionStoreRow, string>) => {
  const { formatMessage: t, formatDate } = useIntl()
  const theme = useTheme()
  const errorColor = theme.palette.error.main

  const gridApiRef = useGridApiContext()
  const { swapStatusesByStoreId } = useContext(GridContext)

  if (!isAutogeneratedRow(row)) {
    const actionCompletionStatus = row.actionStore.completionStatus
    const overdueDate = row.overdueDate
    return (
      <Base>
        <Typography variant="body2" color={needsAttention([actionCompletionStatus]) ? errorColor : undefined}>
          {t(actionCompletionStatusMessages[actionCompletionStatus], {
            date: overdueDate ? formatDate(overdueDate) : null
          })}
        </Typography>
      </Base>
    )
  }

  const storeId = gridApiRef.current.getRowId(row).toString().split('/')[1]
  const swapStatuses = swapStatusesByStoreId[storeId]
  const na = needsAttention(swapStatuses)
  const storeStatus = na
    ? t(commonMessages.needsAttention)
    : swapStatuses.every((status) => status === 'Completed')
      ? t(commonMessages.completed)
      : t(commonMessages.inProgress)

  return (
    <Base>
      <Typography variant="body2" fontWeight={600} color={na ? errorColor : undefined}>
        {storeStatus}
      </Typography>
    </Base>
  )
}
