import type { GridContextParams } from './GridContext'
import type { ActionStoreRow } from '@/hooks/useActionStoreRowsQuery'
import type { DataGridProProps, GridColDef } from '@mui/x-data-grid-pro'
import { useMemo } from 'react'
import { isAutogeneratedRow } from '@mui/x-data-grid-pro'
import dayjs from 'dayjs'
import minMax from 'dayjs/plugin/minMax'
import { CurrencyColumn } from '@/components/grid/CurrencyColumn'
import { DateColumn } from '@/components/grid/DateColumn'
import { TagsColumn } from '@/components/grid/TagsColumn'
import { useCommonLabels } from '@/hooks/useCommonLabels'
import { CategoryHeader } from './CategegoryHeader'
import { NameColumn } from './NameColumn'
import { SwapStatusColumn } from './SwapStatusColumn'
import { SwapStatusHeader } from './SwapStatusHeader'

dayjs.extend(minMax)

export const useGridConfiguration = ({ context }: { context: GridContextParams }) => {
  const { headers } = useCommonLabels()

  const columns = useMemo<GridColDef<ActionStoreRow>[]>(() => {
    return [
      {
        headerName: headers.Tags,
        field: 'productTagsAny',
        valueGetter: (_, row: ActionStoreRow) => row?.actionStore?.productTagsAny,
        renderCell: TagsColumn,
        cellStyle: () => ({ whiteSpace: 'pre' }),
        width: 110,
        sortable: false
      },
      {
        headerName: headers.Category,
        field: 'category',
        valueGetter: (category: ActionStoreRow['category'], row) => {
          return isAutogeneratedRow(row) ? '' : category.externalId
        },
        width: 120,
        renderHeader: CategoryHeader,
        sortable: false
      },
      {
        headerName: headers.Subcategory,
        field: 'subcategory',
        valueGetter: (subcategory: ActionStoreRow['subcategory'], row) =>
          isAutogeneratedRow(row) ? '' : subcategory?.externalId,
        width: 120,
        sortable: false
      },
      {
        headerName: headers.PredictedSalesSeries,
        field: 'actionStore',
        valueGetter: (actionStore: ActionStoreRow['actionStore'], row, _, gridApiRef) => {
          const storeId = gridApiRef.current.getRowId(row).toString().split('/')[1]

          return isAutogeneratedRow(row) ? context.predictedSalesByStoreId[storeId] : actionStore.predictedSales
        },
        width: 190,
        renderCell: CurrencyColumn,
        sortable: false
      },
      {
        headerName: headers.SwapStatus,
        field: 'swapStatus',
        valueGetter: (_, row) => (isAutogeneratedRow(row) ? '' : row.actionStore.completionStatus),
        renderCell: SwapStatusColumn,
        width: 140,
        renderHeader: SwapStatusHeader,
        sortable: false
      },
      {
        headerName: headers.ExecutionDate,
        field: 'completionDate',
        valueGetter: (_, row: ActionStoreRow) => row?.actionStore?.completionDate,
        renderCell: DateColumn,
        width: 130,
        sortable: false
      }
    ]
  }, [
    context.predictedSalesByStoreId,
    headers.Category,
    headers.ExecutionDate,
    headers.PredictedSalesSeries,
    headers.Subcategory,
    headers.SwapStatus,
    headers.Tags
  ])

  const groupingColDef: DataGridProProps['groupingColDef'] = useMemo(
    () => ({ headerName: headers.Name, flex: 1, renderCell: NameColumn }),
    [headers.Name]
  )

  return { columns, headers, groupingColDef }
}
